server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/founderlink_investments
    username: abdulyahiya
    password: yahya9973
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

rabbitmq:
  exchange: founderlink.exchange
  queue:
    investment-created: investment.created.queue
    investment-approved: investment.approved.queue
    startup-approved: startup.approved.queue
  routing-key:
    investment-created: investment.created
    investment-approved: investment.approved
    startup-approved: startup.approved

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
