server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/founderlink_teams
    username: abdulyahiya
    password: yahya9973
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

rabbitmq:
  exchange: founderlink.exchange
  queue:
    team-invite-sent: team.invite.sent.queue
  routing-key:
    team-invite-sent: team.invite.sent

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
